version: '3'
services:
  mongodb:
    image: "mongo:latest"

  tdl-catalogue:
    image: "ipvs/tdl-catalogue:latest"
    environment:
    - MONGODB_PORT=27017
    - MONGODB_IP=mongodb
    ports:
      - "8080:8080"
